languages = {
        "english": "en",
        "afrikaans" : "af",
        "arabic": "ar",
        "bosnian": "bs-Latn",
        "bulgarian": "bg",
        "catalan": "ca",
        "chinese-simplified": "zh-CHS",
        "chinese-traditional": "zh-CHT",
        "croatian": "hr",
        "czech": "cs",
        "danish": "da",
        "dutch": "nl",
        "estonian": "et",
        "finnish": "fi",
        "french" :"fr",
        "german": "de",
        "greek": "el",
        "haitian": "ht",
        "hebrew": "he",
        "hindi": "hi",
        "hmong-daw":"mww",
        "hungarian":"hu",
        "indonesian":"id",
        "italian":"it",
        "japanese":"jp",
        "kiswahili":"sw",
        "klingon":"tlh",
        "klingon-plqad":"tlh-Qaak",
        "korean":"ko",
        "latvian":"lv",
        "lithuanian":"lt",
        "malay":"ms",
        "maltese":"mt",
        "norwegian":"no",
        "persian":"fa",
        "polish":"pl",
        "portugese":"pt",
        "queretaro-otomi":"otq",
        "romanian":"ro",
        "russian":"ru",
        "serbian-cyrillic":"sr-Cyrl",
        "serbian-latin":"sr-Latn",
        "slovak":"sk",
        "slovenian":"sl",
        "spanish":"es",
        "swedish":"sv",
        "thai":"th",
        "turkish":"tr",
        "ukranian":"uk",
        "urdu":"ur",
        "vietnamese":"vi",
        "welsh":"cy",
        "yucatec-maya":"yua"
        }

